export const SIGNIN ='SIGNIN';
export const SIGNOUT = 'SIGNOUT';
export const SIGNINGIN ='SIGNINGIN';
export const SIGNINFAILED ="SIGNINFAILED"
export const NEWUSER ='NEWUSER';
export const REGISTERING ='REGISTERING';
export const REGISTER = 'REGISTER';
export const OLDUSER = "OLDUSER"
// export const CREATENEWROOM = ''
export const FETCHING_ROOMS ="FETCHING_ROOMS"
export const UPDATE_ROOMS ="UPDATE_ROOMS"

export const SELECT_CHAT_ROOM ="SELECT_CHAT_ROOM"
export const UNSELECT_CHAT_ROOM ="UNSELECT_CHAT_ROOM"

export const FETCHING_INVITES="FETCHING_INVITES"
export const GET_INVITES ="GET_INVITES"
export const DELETE_INVITE="DELETE_INVITE"
export const CLEAN_CHAT_REDUCER="CLEAN_CHAT_REDUCER"

export const DELETE_USER = "DELETE_USER"

export const UPDATE_MESSAGES ="UPDATE_MESSAGES"